/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerEstado;
import outstok.conectaBanco;
import Model.ModelEstado;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import outstok.ModeloTabela;

/**
 *
 * @author lukaa
 */
public class Estado extends javax.swing.JInternalFrame {

    conectaBanco conecta = new conectaBanco();
    ModelEstado mod = new ModelEstado();
    ControllerEstado con = new ControllerEstado();

    /**
     * Creates new form NovoJInternalFrame
     */
    public Estado() {
        initComponents();
        conecta.conexao();
        preencherTabela("SELECT * FROM estado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Novo = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Sigla = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaestado = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setForeground(java.awt.Color.white);
        setTitle("Cadastro de Estado");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16/monuments.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Estado");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/website.png"))); // NOI18N
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });

        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/rotate.png"))); // NOI18N
        Update.setEnabled(false);
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/bin.png"))); // NOI18N
        delete.setEnabled(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Nome:");

        Name.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Name.setEnabled(false);
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setText("Sigla:");

        Sigla.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Sigla.setEnabled(false);
        Sigla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiglaActionPerformed(evt);
            }
        });

        id.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        id.setEnabled(false);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setText("Codigo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Sigla, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/save.png"))); // NOI18N
        Save.setEnabled(false);
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Novo)
                    .addComponent(Update)
                    .addComponent(delete)
                    .addComponent(Save))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabelaestado.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tabelaestado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaestado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaestadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaestado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBounds(0, 0, 494, 410);
    }// </editor-fold>//GEN-END:initComponents

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void SiglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiglaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiglaActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        mod.setNome(Name.getText());
        mod.setSigla(Sigla.getText());
        con.Save(mod);

        Name.setText("");
        Sigla.setText("");
        Name.setEnabled(false);
        Sigla.setEnabled(false);
        Save.setEnabled(false);
        delete.setEnabled(false);
        Update.setEnabled(false);
        Novo.setEnabled(true);
        preencherTabela("SELECT * FROM estado");
    }//GEN-LAST:event_SaveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        mod.setId(Integer.parseInt(id.getText()));
        con.Delete(mod);

        Name.setText("");
        Sigla.setText("");
        Name.setEnabled(false);
        Sigla.setEnabled(false);
        Save.setEnabled(false);
        delete.setEnabled(false);
        Update.setEnabled(false);
        Novo.setEnabled(true);
        preencherTabela("SELECT * FROM estado");
    }//GEN-LAST:event_deleteActionPerformed

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
        // TODO add your handling code here:
        Name.setText("");
        Sigla.setText("");
        Name.setEnabled(true);
        Sigla.setEnabled(true);
        Save.setEnabled(true);
        delete.setEnabled(true);
        Update.setEnabled(true);
        Novo.setEnabled(false);
        preencherTabela("SELECT * FROM estado");
    }//GEN-LAST:event_NovoActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here
        mod.setId(Integer.parseInt(id.getText()));
        mod.setNome(Name.getText());
        mod.setSigla(Sigla.getText());
        con.Update(mod);

        Sigla.setText("");
        Name.setEnabled(false);
        Sigla.setEnabled(false);
        Save.setEnabled(false);
        delete.setEnabled(false);
        Update.setEnabled(false);
        Novo.setEnabled(true);
        preencherTabela("SELECT * FROM estado");
    }//GEN-LAST:event_UpdateActionPerformed

    private void tabelaestadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaestadoMouseClicked
        // TODO add your handling code here:
        String n = "" + tabelaestado.getValueAt(tabelaestado.getSelectedRow(), 0);
        conecta.conexao();
        conecta.executaSQL("SELECT * FROM estado WHERE id ='" + n + "'");
        try {
            conecta.rs.first();
            id.setText(String.valueOf(conecta.rs.getInt("id")));
            Name.setText(conecta.rs.getString("nome"));
            Sigla.setText(conecta.rs.getString("sigla"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher os campos!" + ex);
        }
        Name.setEnabled(true);
        Sigla.setEnabled(true);
        Save.setEnabled(true);
        delete.setEnabled(true);
        Update.setEnabled(true);
        Novo.setEnabled(false);
        preencherTabela("SELECT * FROM estado");

    }//GEN-LAST:event_tabelaestadoMouseClicked

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed
    public void preencherTabela(String SQL) {
        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"ID", "Nome", "Sigla"};

        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{
                    conecta.rs.getInt("id"),
                    conecta.rs.getString("nome"),
                    conecta.rs.getString("sigla")});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro preencher a tabela" + ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        tabelaestado.setModel(modelo);
        tabelaestado.getColumnModel().getColumn(0).setPreferredWidth(90);
        tabelaestado.getColumnModel().getColumn(0).setResizable(false);
        tabelaestado.getColumnModel().getColumn(1).setPreferredWidth(240);
        tabelaestado.getColumnModel().getColumn(1).setResizable(false);
        tabelaestado.getColumnModel().getColumn(2).setPreferredWidth(110);
        tabelaestado.getColumnModel().getColumn(2).setResizable(false);
        tabelaestado.getTableHeader().setReorderingAllowed(false);
        tabelaestado.setAutoResizeMode(tabelaestado.AUTO_RESIZE_OFF);
        tabelaestado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name;
    private javax.swing.JButton Novo;
    private javax.swing.JButton Save;
    private javax.swing.JTextField Sigla;
    private javax.swing.JButton Update;
    private javax.swing.JButton delete;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaestado;
    // End of variables declaration//GEN-END:variables
}
