/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Utilitarios.conectaBanco;

/**
 *
 * @author lukaa
 */
public class Principal extends javax.swing.JFrame {

    conectaBanco conecta = new conectaBanco();
        
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Cadastro = new javax.swing.JMenu();
        Estado = new javax.swing.JMenuItem();
        Cidades = new javax.swing.JMenuItem();
        Bairro = new javax.swing.JMenuItem();
        Telefone = new javax.swing.JMenuItem();
        Clientes = new javax.swing.JMenuItem();
        Fornecedor = new javax.swing.JMenuItem();
        Produtos = new javax.swing.JMenuItem();
        Compras = new javax.swing.JMenu();
        Vendas = new javax.swing.JMenu();
        Relatorios = new javax.swing.JMenu();
        Sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OutStok - Sistema de automação de lojas");
        setBackground(new java.awt.Color(0, 0, 0));
        setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        setForeground(java.awt.Color.white);
        setIconImages(null);
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N

        Cadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/browser.png"))); // NOI18N
        Cadastro.setText("Cadastro");
        Cadastro.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N

        Estado.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Estado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/monuments.png"))); // NOI18N
        Estado.setText("Estado");
        Estado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstadoMouseClicked(evt);
            }
        });
        Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoActionPerformed(evt);
            }
        });
        Cadastro.add(Estado);

        Cidades.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Cidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        Cidades.setText("Cidade");
        Cidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidadesActionPerformed(evt);
            }
        });
        Cadastro.add(Cidades);

        Bairro.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Bairro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/holidays.png"))); // NOI18N
        Bairro.setText("Bairro");
        Bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BairroActionPerformed(evt);
            }
        });
        Cadastro.add(Bairro);

        Telefone.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Telefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/smartphone.png"))); // NOI18N
        Telefone.setText("Telefone");
        Cadastro.add(Telefone);

        Clientes.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/team.png"))); // NOI18N
        Clientes.setText("Clientes");
        Cadastro.add(Clientes);

        Fornecedor.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/technology.png"))); // NOI18N
        Fornecedor.setText("Fornecedor");
        Cadastro.add(Fornecedor);

        Produtos.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/barcode.png"))); // NOI18N
        Produtos.setText("Produtos");
        Cadastro.add(Produtos);

        jMenuBar1.add(Cadastro);

        Compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cart.png"))); // NOI18N
        Compras.setText("Compras");
        Compras.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jMenuBar1.add(Compras);

        Vendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sales.png"))); // NOI18N
        Vendas.setText("Vendas");
        Vendas.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jMenuBar1.add(Vendas);

        Relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/news.png"))); // NOI18N
        Relatorios.setText("Relátorios");
        Relatorios.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jMenuBar1.add(Relatorios);

        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/exit.png"))); // NOI18N
        Sair.setText("Sair");
        Sair.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });
        jMenuBar1.add(Sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseWheelMoved

    private void CidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CidadesActionPerformed

    private void BairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BairroActionPerformed

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SairMouseClicked

    private void EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_EstadoActionPerformed

    private void EstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstadoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_EstadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Bairro;
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenuItem Cidades;
    private javax.swing.JMenuItem Clientes;
    private javax.swing.JMenu Compras;
    private javax.swing.JMenuItem Estado;
    private javax.swing.JMenuItem Fornecedor;
    private javax.swing.JMenuItem Produtos;
    private javax.swing.JMenu Relatorios;
    private javax.swing.JMenu Sair;
    private javax.swing.JMenuItem Telefone;
    private javax.swing.JMenu Vendas;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
