/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.ImageIcon;
import outstok.conectaBanco;

/**
 *
 * @author lukaa
 */
public class Principal extends javax.swing.JFrame {

    conectaBanco conecta = new conectaBanco();

    /**
     * Creates new form Principal
     */
    public Principal() {
        setExtendedState(Principal.MAXIMIZED_BOTH);
        initComponents();
        setIcon();
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Cadastro = new javax.swing.JMenu();
        Estado = new javax.swing.JMenuItem();
        Cidades = new javax.swing.JMenuItem();
        Clientes = new javax.swing.JMenuItem();
        Fornecedor = new javax.swing.JMenuItem();
        Produtos = new javax.swing.JMenuItem();
        Vendas = new javax.swing.JMenu();
        Relatorios = new javax.swing.JMenu();
        Sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OutStok - Sistema de automação de lojas");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        setForeground(java.awt.Color.white);
        setIconImages(null);
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 993, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jMenuBar1.setVerifyInputWhenFocusTarget(false);

        Cadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/browser.png"))); // NOI18N
        Cadastro.setText("Cadastro");
        Cadastro.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N

        Estado.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Estado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/monuments.png"))); // NOI18N
        Estado.setText("Estado");
        Estado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstadoMouseClicked(evt);
            }
        });
        Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoActionPerformed(evt);
            }
        });
        Cadastro.add(Estado);

        Cidades.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Cidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/home.png"))); // NOI18N
        Cidades.setText("Cidade");
        Cidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidadesActionPerformed(evt);
            }
        });
        Cadastro.add(Cidades);

        Clientes.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/team.png"))); // NOI18N
        Clientes.setText("Clientes");
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        Cadastro.add(Clientes);

        Fornecedor.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/technology.png"))); // NOI18N
        Fornecedor.setText("Fornecedor");
        Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FornecedorActionPerformed(evt);
            }
        });
        Cadastro.add(Fornecedor);

        Produtos.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/barcode.png"))); // NOI18N
        Produtos.setText("Produtos");
        Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosActionPerformed(evt);
            }
        });
        Cadastro.add(Produtos);

        jMenuBar1.add(Cadastro);

        Vendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/sales.png"))); // NOI18N
        Vendas.setText("Vendas");
        Vendas.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Vendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VendasMouseClicked(evt);
            }
        });
        jMenuBar1.add(Vendas);

        Relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/news.png"))); // NOI18N
        Relatorios.setText("Relátorios");
        Relatorios.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jMenuBar1.add(Relatorios);

        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/exit.png"))); // NOI18N
        Sair.setText("Sair");
        Sair.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });
        jMenuBar1.add(Sair);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("");
        jMenuBar1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1013, 837);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseWheelMoved

    private void CidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidadesActionPerformed
        // TODO add your handling code here:
        Cidade e = new Cidade();
        jPanel1.add(e);
        e.setVisible(true);
    }//GEN-LAST:event_CidadesActionPerformed

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SairMouseClicked

    private void EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoActionPerformed
        // TODO add your handling code here:
        Estado e = new Estado();
        jPanel1.add(e);
        e.setVisible(true);
    }//GEN-LAST:event_EstadoActionPerformed

    private void EstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstadoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_EstadoMouseClicked

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        // TODO add your handling code here:
        Cliente e = new Cliente();
        jPanel1.add(e);
        e.setVisible(true);
    }//GEN-LAST:event_ClientesActionPerformed

    private void FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FornecedorActionPerformed
        // TODO add your handling code here:
        Fornecedor f = new Fornecedor();
        jPanel1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_FornecedorActionPerformed

    private void ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosActionPerformed
        // TODO add your handling code here:
        Produto p = new Produto();
        jPanel1.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_ProdutosActionPerformed

    private void VendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VendasMouseClicked
        // TODO add your handling code here:
        Venda v = new Venda();
        jPanel1.add(v);
        v.setVisible(true);

    }//GEN-LAST:event_VendasMouseClicked

    /**
     * @param args the command line arguments
     */
    public void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("store.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenuItem Cidades;
    private javax.swing.JMenuItem Clientes;
    private javax.swing.JMenuItem Estado;
    private javax.swing.JMenuItem Fornecedor;
    private javax.swing.JMenuItem Produtos;
    private javax.swing.JMenu Relatorios;
    private javax.swing.JMenu Sair;
    private javax.swing.JMenu Vendas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
