/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerProduto;
import Model.ModelProduto;
import outstok.conectaBanco;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import outstok.ModeloTabela;

/**
 *
 * @author lukaa
 */
public class Produto extends javax.swing.JInternalFrame {

    conectaBanco conecta = new conectaBanco();
    ModelProduto mod = new ModelProduto();
    ControllerProduto con = new ControllerProduto();
    String preenche = "SELECT * FROM produtos, fornecedor WHERE Fornecedor_id = fornecedor.id ";

    /**
     * Creates new form NovoJInternalFrame
     */
    public Produto() {
        initComponents();
        conecta.conexao();
        preencherTabela(preenche);
        conecta.executaSQL("SELECT * FROM fornecedor ORDER BY nome");
        jComboBoxF.removeAllItems();
        try {
            conecta.rs.first();
            do {
                jComboBoxF.addItem(conecta.rs.getString("nome"));
            } while (conecta.rs.next());
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, "Erro a preencher lista");
        }
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Novo = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Codigo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Observacao = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Preco_custo = new javax.swing.JFormattedTextField();
        Preco_venda = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        Quantidade = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        Estoque = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxF = new javax.swing.JComboBox<>();
        Save = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaestado = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setForeground(java.awt.Color.white);
        setTitle("Cadastro de Produtos");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16/barcode.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Produtos");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/website.png"))); // NOI18N
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });

        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/rotate.png"))); // NOI18N
        Update.setEnabled(false);
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/bin.png"))); // NOI18N
        delete.setEnabled(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Nome:");

        Name.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Name.setEnabled(false);
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        id.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        id.setEnabled(false);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setText("Codigo:");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setText("Preço Venda:");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel9.setText("Codigo:");

        Codigo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Codigo.setEnabled(false);
        Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel14.setText("Observação:");

        Observacao.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Observacao.setEnabled(false);
        Observacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObservacaoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel12.setText("Preço Custo:");

        Preco_custo.setEnabled(false);
        Preco_custo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        Preco_venda.setEnabled(false);
        Preco_venda.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel7.setText("Quantidade:");

        Quantidade.setEnabled(false);
        Quantidade.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel8.setText("Estoque Min:");

        Estoque.setEnabled(false);
        Estoque.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel11.setText("Fornecedor:");

        jComboBoxF.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jComboBoxF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Codigo)
                    .addComponent(Name)
                    .addComponent(jLabel4)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Preco_custo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Preco_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Observacao, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jComboBoxF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Preco_custo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Preco_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Estoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Observacao)))
                .addContainerGap())
        );

        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/save.png"))); // NOI18N
        Save.setEnabled(false);
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Novo)
                    .addComponent(Update)
                    .addComponent(delete)
                    .addComponent(Save))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(7, 7, 7))
        );

        tabelaestado.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tabelaestado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaestado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaestadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaestado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(231, 231, 231))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 729, 799);
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        mod.setNome(Name.getText());
        mod.setPreco_venda(Float.parseFloat(Preco_venda.getText()));
        mod.setPreco_custo(Float.parseFloat(Preco_custo.getText()));
        mod.setQuantidade(Integer.parseInt(Quantidade.getText()));
        mod.setCodigo(Codigo.getText());
        mod.setEstoque(Integer.parseInt(Estoque.getText()));
        mod.setObservacao(Observacao.getText());
        try {
            conecta.executaSQL("SELECT * FROM fornecedor where nome='" + jComboBoxF.getSelectedItem()+ "'");
            conecta.rs.first();
            String nome;
            nome = conecta.rs.getString("nome");
            mod.setFornecedor_id(conecta.rs.getInt("fornecedor.id"));
            con.Save(mod);
        } catch (SQLException ex) {
            Logger.getLogger(Produto.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        Name.setText("");
        Preco_venda.setText("");
        Preco_custo.setText("");
        Quantidade.setText("");
        Codigo.setText("");
        Estoque.setText("");
        Observacao.setText("");
        Name.setEnabled(false);
        Preco_venda.setEnabled(false);
        Preco_custo.setEnabled(false);
        Quantidade.setEnabled(false);
        Codigo.setEnabled(false);
        Observacao.setEnabled(false);
        jComboBoxF.setEnabled(false);
        Save.setEnabled(false);
        delete.setEnabled(false);
        Update.setEnabled(false);
        Novo.setEnabled(true);
        preencherTabela(preenche);
    }//GEN-LAST:event_SaveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        mod.setId(Integer.parseInt(id.getText()));
        con.Delete(mod);
        Name.setText("");
        Preco_venda.setText("");
        Preco_custo.setText("");
        Quantidade.setText("");
        Codigo.setText("");
        Estoque.setText("");
        Observacao.setText("");
        Name.setEnabled(false);
        Preco_venda.setEnabled(false);
        Preco_custo.setEnabled(false);
        Quantidade.setEnabled(false);
        Codigo.setEnabled(false);
        Observacao.setEnabled(false);
        jComboBoxF.setEnabled(false);
        Save.setEnabled(false);
        delete.setEnabled(false);
        Update.setEnabled(false);
        Novo.setEnabled(true);
        preencherTabela(preenche);
    }//GEN-LAST:event_deleteActionPerformed

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
        // TODO add your handling code here:
        Name.setText("");
        Preco_venda.setText("");
        Preco_custo.setText("");
        Quantidade.setText("");
        Codigo.setText("");
        Estoque.setText("");
        Observacao.setText("");
        Name.setEnabled(true);
        Preco_venda.setEnabled(true);
        Preco_custo.setEnabled(true);
        Quantidade.setEnabled(true);
        Codigo.setEnabled(true);
        Observacao.setEnabled(true);
        Estoque.setEnabled(true);
        jComboBoxF.setEnabled(true);
        Save.setEnabled(true);
        delete.setEnabled(true);
        Update.setEnabled(true);
        Novo.setEnabled(false);
        preencherTabela(preenche);
    }//GEN-LAST:event_NovoActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        mod.setId(Integer.parseInt(id.getText()));
        mod.setNome(Name.getText());
        mod.setPreco_venda(Float.parseFloat(Preco_venda.getText()));
        mod.setPreco_custo(Float.parseFloat(Preco_custo.getText()));
        mod.setQuantidade(Integer.parseInt(Quantidade.getText()));
        mod.setCodigo(Codigo.getText());
        mod.setEstoque(Integer.parseInt(Estoque.getText()));
        mod.setObservacao(Observacao.getText());
        try {
            conecta.executaSQL("SELECT * FROM fornecedor where nome='" + jComboBoxF.getSelectedItem() + "'");
            conecta.rs.first();
            mod.setFornecedor_id(conecta.rs.getInt("fornecedor.id"));
            con.Update(mod);
        } catch (SQLException ex) {
            Logger.getLogger(Produto.class.getName()).log(Level.SEVERE, null, ex);
        }
        Name.setText("");
        Preco_venda.setText("");
        Preco_custo.setText("");
        Quantidade.setText("");
        Codigo.setText("");
        Estoque.setText("");
        Observacao.setText("");
        Name.setEnabled(false);
        Preco_venda.setEnabled(false);
        Preco_custo.setEnabled(false);
        Quantidade.setEnabled(false);
        Codigo.setEnabled(false);
        Observacao.setEnabled(false);
        jComboBoxF.setEnabled(false);
        Save.setEnabled(false);
        delete.setEnabled(false);
        Update.setEnabled(false);
        Novo.setEnabled(true);
        preencherTabela(preenche);
    }//GEN-LAST:event_UpdateActionPerformed

    private void tabelaestadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaestadoMouseClicked
        // TODO add your handling code here:
        String n = "" + tabelaestado.getValueAt(tabelaestado.getSelectedRow(), 0);
        conecta.conexao();
        conecta.executaSQL("SELECT * FROM produtos WHERE id ='" + n + "'");
        try {
            conecta.rs.first();
            id.setText(String.valueOf(conecta.rs.getInt("id")));
            Name.setText(conecta.rs.getString("nome"));
            Preco_venda.setText(String.valueOf(conecta.rs.getString("preco_venda")));
            Preco_custo.setText(String.valueOf(conecta.rs.getString("preco_custo")));
            Quantidade.setText(String.valueOf(conecta.rs.getString("quantidade")));
            Codigo.setText(conecta.rs.getString("codigo"));
            Estoque.setText(String.valueOf(conecta.rs.getString("estoque_minimo")));
            Observacao.setText(conecta.rs.getString("observacao"));
            int f = conecta.rs.getInt("Fornecedor_id");
            conecta.executaSQL("SELECT * FROM fornecedor where id = '" + f + "'");
            conecta.rs.first();
            jComboBoxF.setSelectedItem(conecta.rs.getString("fornecedor.nome"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher os campos!" + ex);
        }
        Name.setEnabled(true);
        Preco_venda.setEnabled(true);
        Preco_custo.setEnabled(true);
        Quantidade.setEnabled(true);
        Codigo.setEnabled(true);
        Observacao.setEnabled(true);
        jComboBoxF.setEnabled(true);
        Estoque.setEnabled(true);
        Save.setEnabled(true);
        delete.setEnabled(true);
        Update.setEnabled(true);
        Novo.setEnabled(false);
        preencherTabela(preenche);
    }//GEN-LAST:event_tabelaestadoMouseClicked

    private void ObservacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObservacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObservacaoActionPerformed

    private void CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed
    public void preencherTabela(String SQL) {
        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"ID", "Nome", "Preço Venda", "Preço Custo", "Quantidade", "Estoque", "Observaçao",
            "Codigo", "Fornecedor"
        };

        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{
                    conecta.rs.getInt("id"),
                    conecta.rs.getString("produtos.nome"),
                    conecta.rs.getString("produtos.preco_venda"),
                    conecta.rs.getString("produtos.preco_custo"),
                    conecta.rs.getString("produtos.quantidade"),
                    conecta.rs.getString("produtos.estoque_minimo"),
                    conecta.rs.getString("produtos.observacao"),
                    conecta.rs.getString("produtos.codigo"),
                    conecta.rs.getString("fornecedor.nome")
                    });
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro preencher a tabela" + ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        tabelaestado.setModel(modelo);
        tabelaestado.setAutoResizeMode(tabelaestado.AUTO_RESIZE_ALL_COLUMNS);
        tabelaestado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Codigo;
    private javax.swing.JFormattedTextField Estoque;
    private javax.swing.JTextField Name;
    private javax.swing.JButton Novo;
    private javax.swing.JTextField Observacao;
    private javax.swing.JFormattedTextField Preco_custo;
    private javax.swing.JFormattedTextField Preco_venda;
    private javax.swing.JFormattedTextField Quantidade;
    private javax.swing.JButton Save;
    private javax.swing.JButton Update;
    private javax.swing.JButton delete;
    private javax.swing.JTextField id;
    private javax.swing.JComboBox<String> jComboBoxF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaestado;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
