/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerVenda;
import Model.ModelVenda;
import java.sql.PreparedStatement;
import outstok.conectaBanco;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import outstok.ModeloTabela;
import static outstok.conectaBanco.conn;

/**
 *
 * @author lukaa
 */
public class Venda extends javax.swing.JInternalFrame {

    conectaBanco conecta = new conectaBanco();
    ModelVenda mod = new ModelVenda();
    ControllerVenda con = new ControllerVenda();
    int flag = 1;
    float preco;
    int codVenda;

    /**
     * Creates new form NovoJInternalFrame
     */
    public Venda() {
        initComponents();
        conecta.conexao();

        try {
            PreparedStatement pst = conn.prepareStatement("INSERT INTO venda "
                    + "(valor_venda) VALUES (?)");
            pst.setFloat(1, 0);
            pst.execute();
            conecta.executaSQL("SELECT * FROM venda");
            conecta.rs.last();
            codVenda = conecta.rs.getInt("id");
        } catch (SQLException ex) {
            Logger.getLogger(Venda.class.getName()).log(Level.SEVERE, null, ex);
        }
        ;
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date hoje = new Date();
        jFormattedTextField1.setText(df.format(hoje));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Cliente = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaestado1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        Preco_venda = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Quantidade = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaestado = new javax.swing.JTable();
        Codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        SubTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Desconto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Total = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Recebido = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Troco = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setForeground(java.awt.Color.white);
        setTitle("Venda de Produtos");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16/cart.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel9.setText("Pesquisar Produto:");

        Name.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Name.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                NameInputMethodTextChanged(evt);
            }
        });
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NameKeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/search (1).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel10.setText("Pesquisar Cliente:");

        Cliente.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/search (1).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tabelaestado1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tabelaestado1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaestado1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaestado1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaestado1);

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setText("Valor:");

        Preco_venda.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Preco_venda.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                Preco_vendaInputMethodTextChanged(evt);
            }
        });
        Preco_venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Preco_vendaActionPerformed(evt);
            }
        });
        Preco_venda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Preco_vendaKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel12.setText("Quantidade:");

        Quantidade.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Quantidade.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                QuantidadeInputMethodTextChanged(evt);
            }
        });
        Quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantidadeActionPerformed(evt);
            }
        });
        Quantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                QuantidadeKeyPressed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/plus.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Preco_venda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButton2))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Preco_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setEnabled(false);

        tabelaestado.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tabelaestado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaestado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaestadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaestado);

        Codigo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CodigoFocusLost(evt);
            }
        });
        Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Codigo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Codigo))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );

        SubTotal.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        SubTotal.setEnabled(false);
        SubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubTotalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setText("Sub Total:");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setText("Desconto:");

        Desconto.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        Desconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DescontoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DescontoFocusLost(evt);
            }
        });
        Desconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescontoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel13.setText("Total:");

        Total.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        Total.setEnabled(false);
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel15.setText("Recebido:");

        Recebido.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        Recebido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                RecebidoFocusLost(evt);
            }
        });
        Recebido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecebidoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel16.setText("Forma:");

        Troco.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        Troco.setEnabled(false);
        Troco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrocoActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Á Vista", "Prazo", "Cheque", "Cartão Crédtio", "Débito" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel17.setText("Troco:");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/cart.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/64/exit.png"))); // NOI18N

        jFormattedTextField1.setBorder(null);
        jFormattedTextField1.setEnabled(false);
        jFormattedTextField1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(Troco)
                            .addComponent(Recebido)
                            .addComponent(Total)
                            .addComponent(Desconto)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel5)
                            .addComponent(SubTotal)
                            .addComponent(jLabel17)
                            .addComponent(jComboBox1, 0, 193, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1)
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Desconto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Recebido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Troco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jButton4)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 853, 799);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaestadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaestadoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tabelaestadoMouseClicked

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoActionPerformed

        try {
            // TODO add your handling code here:
            conecta.executaSQL("SELECT * FROM `produtos` WHERE codigo = '" + Codigo.getText() + "'");
            conecta.rs.first();
            int estoque = conecta.rs.getInt("quantidade");
            if (estoque >= 1) {
                mod.setNome_produto(conecta.rs.getString("nome"));
                mod.setQuantidade(1);
                mod.setId(codVenda);
                con.adicionaItem(mod);
                preencherTabela3("SELECT * FROM `produtos_has_venda`,produtos, venda WHERE `produtos_id`=produtos.id and venda_id = venda.id and venda.id='" + codVenda + "'");
            } else {
                JOptionPane.showMessageDialog(null, "Estoque Indiponivel");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Venda.class.getName()).log(Level.SEVERE, null, ex);
        }
        Codigo.setText("");
    }//GEN-LAST:event_CodigoActionPerformed

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteActionPerformed

    private void tabelaestado1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaestado1MouseClicked
        // TODO add your handling code here:

        if (flag == 1) {
            String nome_cliente = "" + tabelaestado1.getValueAt(tabelaestado1.getSelectedRow(), 1);
            Cliente.setText(nome_cliente);
        } else {
            String nome_produto = "" + tabelaestado1.getValueAt(tabelaestado1.getSelectedRow(), 1);
            conecta.executaSQL("SELECT * FROM produtos WHERE nome = '" + nome_produto + "'");
            try {
                conecta.rs.first();
                Preco_venda.setText(String.valueOf(conecta.rs.getFloat("preco_venda")));
                Name.setText(nome_produto);
                Quantidade.setText("1");
            } catch (SQLException ex) {
                Logger.getLogger(Venda.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_tabelaestado1MouseClicked

    private void SubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubTotalActionPerformed

    private void DescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescontoActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalActionPerformed

    private void RecebidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecebidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecebidoActionPerformed

    private void TrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrocoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        flag = 2;
        preencherTabela2("SELECT * FROM `produtos` WHERE nome LIKE '%" + Name.getText() + "%'");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        flag = 1;
        preencherTabela("SELECT * FROM `cliente` WHERE nome LIKE '%" + Cliente.getText() + "%'");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void NameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_NameInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_NameInputMethodTextChanged

    private void NameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameKeyPressed

    private void CodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CodigoFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_CodigoFocusLost

    private void Preco_vendaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_Preco_vendaInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Preco_vendaInputMethodTextChanged

    private void Preco_vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Preco_vendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Preco_vendaActionPerformed

    private void Preco_vendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Preco_vendaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Preco_vendaKeyPressed

    private void QuantidadeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_QuantidadeInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantidadeInputMethodTextChanged

    private void QuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantidadeActionPerformed

    private void QuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantidadeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantidadeKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int estoque;
        try {
            conecta.executaSQL("SELECT * FROM produtos WHERE nome = '" + Name.getText() + "'");
            conecta.rs.first();
            estoque = conecta.rs.getInt("quantidade");
            if (estoque >= Integer.parseInt(Quantidade.getText())) {
                mod.setNome_produto(Name.getText());
                mod.setQuantidade(Integer.parseInt(Quantidade.getText()));
                mod.setId(codVenda);
                con.adicionaItem(mod);
                preencherTabela3("SELECT * FROM `produtos_has_venda`,produtos, venda WHERE `produtos_id`=produtos.id and venda_id = venda.id and venda.id='" + codVenda + "'");
            } else {
                JOptionPane.showMessageDialog(null, "Estoque indisponivel");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Venda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void DescontoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DescontoFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_DescontoFocusGained

    private void DescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DescontoFocusLost
        // TODO add your handling code here:       
        float preco = Float.parseFloat(SubTotal.getText());
        int desconto = Integer.parseInt(Desconto.getText());
        float resultado = (preco * desconto) / 100;
        float total = preco - resultado;
        Total.setText(String.valueOf(total));

    }//GEN-LAST:event_DescontoFocusLost

    private void RecebidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RecebidoFocusLost
        // TODO add your handling code here:
        float preco = Float.parseFloat(Total.getText());
        float dinheiro = Float.parseFloat(Recebido.getText());
        float total = dinheiro - preco;
        Troco.setText(String.valueOf(total));


    }//GEN-LAST:event_RecebidoFocusLost

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        mod.setData_venda(jFormattedTextField1.getText());
        mod.setValor(Float.parseFloat(Total.getText()));
        mod.setId(codVenda);
        mod.setForma(String.valueOf(jComboBox1.getSelectedItem()));        
        con.finalizarVenda(mod);
        dispose();

    }//GEN-LAST:event_jButton4ActionPerformed
    public void preencherTabela(String SQL) {
        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"ID", "Nome", "Telefone", " Celular", "Endereço",};

        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{
                    conecta.rs.getInt("id"),
                    conecta.rs.getString("nome"),
                    conecta.rs.getString("telefone"),
                    conecta.rs.getString("celular"),
                    conecta.rs.getString("endereco"),});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro preencher a tabela" + ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        tabelaestado1.setModel(modelo);
        tabelaestado1.setAutoResizeMode(tabelaestado1.AUTO_RESIZE_ALL_COLUMNS);
        tabelaestado1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void preencherTabela2(String SQL) {
        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"ID", "Nome", "Preço", " Quantidade"};

        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{
                    conecta.rs.getInt("id"),
                    conecta.rs.getString("nome"),
                    conecta.rs.getString("preco_venda"),
                    conecta.rs.getString("quantidade"),});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro preencher a tabela" + ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        tabelaestado1.setModel(modelo);
        tabelaestado1.setAutoResizeMode(tabelaestado1.AUTO_RESIZE_ALL_COLUMNS);
        tabelaestado1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    public void preencherTabela3(String SQL) {
        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"Nome", "Preço", " Quantidade", "Total"};

        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();

            do {
                int vendaQtd = conecta.rs.getInt("produtos_has_venda.quantidade");
                float valPro = conecta.rs.getFloat("produtos.preco_venda");
                dados.add(new Object[]{
                    conecta.rs.getString("produtos.nome"),
                    conecta.rs.getString("produtos.preco_venda"),
                    conecta.rs.getString("produtos_has_venda.quantidade"),
                    valPro * vendaQtd});
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro preencher a tabela" + ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        tabelaestado.setModel(modelo);
        tabelaestado.setAutoResizeMode(tabelaestado.AUTO_RESIZE_ALL_COLUMNS);
        tabelaestado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        somaProduto();

    }

    public void somaProduto() {
        float total = 0;
        conecta.executaSQL("SELECT * FROM `produtos_has_venda`,produtos, venda WHERE `produtos_id`=produtos.id and venda_id = venda.id and venda.id='" + codVenda + "'");
        try {
            while (conecta.rs.next()) {
                int qtd = conecta.rs.getInt("produtos_has_venda.quantidade");
                float preco = conecta.rs.getFloat("produtos.preco_venda");
                total = total + qtd * preco;
            }
            SubTotal.setText(String.valueOf(total));

        } catch (SQLException ex) {
            Logger.getLogger(Venda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cliente;
    private javax.swing.JTextField Codigo;
    private javax.swing.JTextField Desconto;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Preco_venda;
    private javax.swing.JTextField Quantidade;
    private javax.swing.JTextField Recebido;
    private javax.swing.JTextField SubTotal;
    private javax.swing.JTextField Total;
    private javax.swing.JTextField Troco;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaestado;
    private javax.swing.JTable tabelaestado1;
    // End of variables declaration//GEN-END:variables

}
